#!/bin/bash -e
echo "Generating STACK_RESOURCE_NAME"
STACK_RESOURCE_NAME=$(get_stack_resource_name "$ENV_NAME" "$SERVICE_NAME" "$RESOURCE_NAME" "$REGION" "$NAME")
echo "STACK_RESOURCE_NAME: $STACK_RESOURCE_NAME"
